{
 "title": "Spark Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "spark_ui_domain",
    "query": "spark-history.prd-k8s.chrissng.net"
   }
  ]
 },
 "panels": [
  {
   "title": "# of Spark jobs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kube_pod_labels{label_spark_role=\"executor\"} and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_spark_app_selector))"
    }
   ]
  },
  {
   "title": "% of nodes utilized",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kube_pod_info and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1) and on(pod) (kube_pod_labels{label_spark_role=\"executor\"})) by (node)) / count(kube_node_labels and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))"
    }
   ]
  },
  {
   "title": "# of executor pods",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(kube_pod_labels{label_spark_role=\"executor\"} and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_spark_app_selector , namespace))"
    }
   ]
  },
  {
   "title": "Memory utilization %",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n   (sum(label_replace(container_memory_usage_bytes{container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace))\n   and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n   and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\n/ \nsum(\n   (sum(kube_pod_container_resource_requests_memory_bytes{}) by (pod, namespace))\n   and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n   and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))"
    }
   ]
  },
  {
   "title": "CPU utilization %",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(\n    (sum(label_replace(rate(container_cpu_usage_seconds_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)))\n/ \n(sum(\n    (sum(kube_pod_container_resource_requests_cpu_cores{}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)))"
    }
   ]
  },
  {
   "title": "# of executors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_labels{label_spark_role=\"executor\"} and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_spark_app_selector , namespace)",
     "legendFormat": "{{ namespace }}, {{ label_spark_app_selector }}"
    }
   ]
  },
  {
   "title": "Recent pod state counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(kube_pod_status_phase and on (pod) kube_pod_labels{label_spark_role=\"executor\"} and on(pod) (kube_pod_created >= (time() - $__range_s))) by (phase))",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Memory utilization %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    (sum(label_replace(container_memory_usage_bytes{container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace) /1024 / 1024 / 1024) \n/ \n(sum(\n    (sum(kube_pod_container_resource_requests_memory_bytes{}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) \nby (namespace) / 1024 / 1024 / 1024)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU utilization %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    (sum(label_replace(rate(container_cpu_usage_seconds_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))\n/ \n(sum(\n    (sum(kube_pod_container_resource_requests_cpu_cores{}) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(\n    (sum(label_replace(rate(container_network_receive_bytes_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))",
     "legendFormat": "IN {{ namespace }}"
    },
    {
     "expr": "- (sum(\n    (sum(label_replace(rate(container_network_transmit_bytes_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace))\n    and on(pod) kube_pod_labels{label_spark_role=\"executor\"} \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (namespace))",
     "legendFormat": "OUT {{ namespace }}"
    }
   ]
  },
  {
   "title": "Active Spark jobs",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "min(kube_pod_start_time * 1000 \n+ on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \nand on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_spark_app_selector)"
    },
    {
     "expr": "time() - min(kube_pod_start_time \n+ on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \nand on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_spark_app_selector)"
    },
    {
     "expr": "count(kube_pod_labels{label_spark_role=\"executor\"} and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_spark_app_selector, namespace)"
    },
    {
     "expr": "(sum(\n    sum(label_replace(container_memory_usage_bytes{container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace)\n    + on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (label_spark_app_selector, namespace))"
    },
    {
     "expr": "(sum(\n    sum(kube_pod_container_resource_requests_memory_bytes{}) by (pod, namespace) \n    + on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (label_spark_app_selector, namespace))"
    },
    {
     "expr": "(sum(\n    sum(label_replace(rate(container_cpu_usage_seconds_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace) \n    + on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (label_spark_app_selector, namespace))"
    },
    {
     "expr": "(sum(\n    sum(kube_pod_container_resource_requests_cpu_cores{}) by (pod, namespace) \n    + on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (label_spark_app_selector, namespace))"
    },
    {
     "expr": "(sum(\n    sum(label_replace(rate(container_network_receive_bytes_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace) \n    + on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (label_spark_app_selector, namespace))"
    },
    {
     "expr": "(sum(\n    sum(label_replace(rate(container_network_transmit_bytes_total{container_name!=\"\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod, namespace) \n    + on(pod) group_left(label_spark_app_selector) (0 * kube_pod_labels{label_spark_role=\"executor\"}) \n    and on(pod) (kube_pod_status_phase{phase=\"Running\"} == 1))\nby (label_spark_app_selector, namespace))"
    }
   ]
  }
 ]
}